.TH "zoxide-init" "1" "2021-04-12" "zoxide" "zoxide"
.SH NAME
zoxide-init - generate shell configuration for zoxide
.SH SYNOPSIS
.B zoxide init \fISHELL [OPTIONS]\fR
.SH DESCRIPTION
To initialize zoxide on your shell:
.TP
.B bash
Add this to your configuration (usually \fI~/.bashrc\fR):
.sp
.nf
    \fBeval "$(zoxide init bash)"\fR
.fi
.TP
.B elvish
Add this to your configuration (usually \fI~/.elvish/rc.elv\fR):
.sp
.nf
    \fBeval $(zoxide init elvish | slurp)\fR
.fi
Note: zoxide only supports elvish v0.16.0 and above.
.TP
.B fish
Add this to your configuration (usually \fI~/.config/fish/config.fish\fR):
.sp
.nf
    \fBzoxide init fish | source\fR
.fi
.TP
.B nushell
Add this to your configuration (find it by running \fBconfig path\fR in
Nushell):
.sp
.nf
    \fBstartup = ["zoxide init nushell --hook prompt | save ~/.zoxide.nu", "source ~/.zoxide.nu"]\fR
.fi
.sp
Note: zoxide only supports Nushell v0.36.0 and above.
.TP
.B powershell
Add this to your configuration (find it by running \fBecho $profile\fR in
PowerShell):
.sp
.nf
    \fBInvoke-Expression (& {
        $hook = if ($PSVersionTable.PSVersion.Major -lt 6) { 'prompt' } else { 'pwd' }
        (zoxide init --hook $hook powershell) -join "`n"
    })\fR
.fi
.TP
.B xonsh
Add this to your configuration (usually \fI~/.xonshrc\fR):
.sp
.nf
    \fBexecx($(zoxide init xonsh), 'exec', __xonsh__.ctx, filename='zoxide')\fR
.fi
.TP
.B zsh
Add this to your configuration (usually \fI~/.zshrc\fR):
.sp
.nf
    \fBeval "$(zoxide init zsh)"\fR
.fi
.TP
.B any POSIX shell
.sp
Add this to your configuration:
.sp
.nf
    \fBeval "$(zoxide init posix --hook prompt)"\fR
.fi
.SH OPTIONS
.TP
.B --cmd
Changes the prefix of predefined aliases (\fBz\fR, \fBzi\fR).
.br
e.g. --cmd j would change the aliases to j and ji respectively.
.TP
.B -h, --help
Print help information.
.TP
.B --hook \fIHOOK\fR
Changes how often zoxide increments a directory's score:
.TS
tab(|);
l l.
    \fInone\fR|Never
    \fIprompt\fR|At every shell prompt
    \fIpwd\fR|Whenever the directory is changed
.TE
.TP
.B --no-aliases
Don't define extra aliases (\fBz\fR, \fBzi\fR). These functions will still be
available in your shell as \fB__zoxide_z\fR and \fB__zoxide_zi\fR, should you
choose to redefine them.
.SH REPORTING BUGS
For any issues, feature requests, or questions, please visit:
.sp
    \fIhttps://github.com/ajeetdsouza/zoxide/issues\fR
.SH AUTHOR
Ajeet D'Souza <\fI98ajeet@gmail.com\fR>
