.TH "ZOXIDE" "1" "2021-04-12" "" "zoxide"
.SH NAME
\fBzoxide-import\fR - import data from other tools
.SH SYNOPSIS
.B zoxide import PATH --from FORMAT [OPTIONS]
.SH OPTIONS
.TP
.B --from FORMAT
The format of the database being imported:
.TS
tab(|);
l l.
    \fBautojump\fR
    \fBz\fR|(for \fBfasd\fR, \fBz\fR, \fBz.lua\fR, or \fBzsh-z\fR)
.TE
.sp
Note: zoxide only imports paths from autojump, since its matching
algorithm is too different to import the scores.
.TP
.B -h, --help
Print help information.
.TP
.B --merge
By default, the import fails if the current database is not already empty. This
option merges imported data into the existing database.
.SH REPORTING BUGS
For any issues, feature requests, or questions, please visit:
.sp
\fBhttps://github.com/ajeetdsouza/zoxide/issues\fR
.SH AUTHOR
Ajeet D'Souza \fB<98ajeet@gmail.com>\fR
