.TH "ZOXIDE" "1" "2021-04-12" "" "zoxide"
.SH NAME
\fBzoxide-import\fR - import data from other tools
.SH SYNOPSIS
.B zoxide import <PLUGIN> [OPTIONS]
.SH PLUGINS
.TS
tab(|);
l l.
\fBatuin\fR|(Atuin shell history)
\fBautojump\fR|(Autojump)
\fBfasd\fR|(Fasd)
\fBz\fR|(Z)
\fBz.lua\fR|(Z.lua)
\fBzsh-z\fR|(Zsh-z)
.TE
.sp
Note: zoxide only imports paths from autojump, since its matching
algorithm is too different to import the scores.
.SH OPTIONS
.TP
.B --merge
By default, the import fails if the current database is not already empty. This
option merges imported data into the existing database.
.TP
.B -h, --help
Print help information.
.SH REPORTING BUGS
For any issues, feature requests, or questions, please visit:
.sp
\fBhttps://github.com/ajeetdsouza/zoxide/issues\fR
.SH AUTHOR
Ajeet D'Souza \fB<98ajeet@gmail.com>\fR
